# Generated by Codex on 2026-06-28

from django.db import migrations, models


def normalize_title(question):
    normalized_title = " ".join(question.split())
    if len(normalized_title) > 80:
        return f"{normalized_title[:77].rstrip()}..."
    return normalized_title


def backfill_chat_titles(apps, schema_editor):
    ChatSession = apps.get_model("ai_tutor", "ChatSession")
    ChatMessage = apps.get_model("ai_tutor", "ChatMessage")

    for session in ChatSession.objects.filter(title=""):
        first_question = (
            ChatMessage.objects.filter(session=session, sender="student")
            .order_by("created_at", "id")
            .values_list("message_text", flat=True)
            .first()
        )
        if not first_question:
            continue
        session.title = normalize_title(first_question)
        session.save(update_fields=["title"])


class Migration(migrations.Migration):

    dependencies = [
        ("ai_tutor", "0002_remove_resourcechunk_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="title",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.RunPython(backfill_chat_titles, migrations.RunPython.noop),
    ]
