# Generated by Django 5.2 on 2026-07-06 22:20

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tutor', '0003_chatsession_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcechunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
