# Generated by Django 5.2 on 2026-06-19 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tutor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcechunk',
            name='embedding',
        ),
    ]
