/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectRoleRouteImport } from './routes/select-role'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnerRouteImport } from './routes/learner'
import { Route as IndexRouteImport } from './routes/index'

const SelectRoleRoute = SelectRoleRouteImport.update({
  id: '/select-role',
  path: '/select-role',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerRoute = LearnerRouteImport.update({
  id: '/learner',
  path: '/learner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learner': typeof LearnerRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/select-role': typeof SelectRoleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learner': typeof LearnerRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/select-role': typeof SelectRoleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learner': typeof LearnerRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/select-role': typeof SelectRoleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/learner' | '/login' | '/register' | '/select-role'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/learner' | '/login' | '/register' | '/select-role'
  id: '__root__' | '/' | '/learner' | '/login' | '/register' | '/select-role'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnerRoute: typeof LearnerRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SelectRoleRoute: typeof SelectRoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-role': {
      id: '/select-role'
      path: '/select-role'
      fullPath: '/select-role'
      preLoaderRoute: typeof SelectRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner': {
      id: '/learner'
      path: '/learner'
      fullPath: '/learner'
      preLoaderRoute: typeof LearnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnerRoute: LearnerRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SelectRoleRoute: SelectRoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
