/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectRoleRouteImport } from './routes/select-role'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnerRouteImport } from './routes/learner'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorResourcesRouteImport } from './routes/tutor.resources'
import { Route as TutorOverviewRouteImport } from './routes/tutor.overview'
import { Route as TutorDigitalTwinRouteImport } from './routes/tutor.digital-twin'
import { Route as TutorCoursesRouteImport } from './routes/tutor.courses'

const SelectRoleRoute = SelectRoleRouteImport.update({
  id: '/select-role',
  path: '/select-role',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerRoute = LearnerRouteImport.update({
  id: '/learner',
  path: '/learner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorResourcesRoute = TutorResourcesRouteImport.update({
  id: '/tutor/resources',
  path: '/tutor/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorOverviewRoute = TutorOverviewRouteImport.update({
  id: '/tutor/overview',
  path: '/tutor/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorDigitalTwinRoute = TutorDigitalTwinRouteImport.update({
  id: '/tutor/digital-twin',
  path: '/tutor/digital-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorCoursesRoute = TutorCoursesRouteImport.update({
  id: '/tutor/courses',
  path: '/tutor/courses',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learner': typeof LearnerRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/select-role': typeof SelectRoleRoute
  '/tutor/courses': typeof TutorCoursesRoute
  '/tutor/digital-twin': typeof TutorDigitalTwinRoute
  '/tutor/overview': typeof TutorOverviewRoute
  '/tutor/resources': typeof TutorResourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learner': typeof LearnerRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/select-role': typeof SelectRoleRoute
  '/tutor/courses': typeof TutorCoursesRoute
  '/tutor/digital-twin': typeof TutorDigitalTwinRoute
  '/tutor/overview': typeof TutorOverviewRoute
  '/tutor/resources': typeof TutorResourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learner': typeof LearnerRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/select-role': typeof SelectRoleRoute
  '/tutor/courses': typeof TutorCoursesRoute
  '/tutor/digital-twin': typeof TutorDigitalTwinRoute
  '/tutor/overview': typeof TutorOverviewRoute
  '/tutor/resources': typeof TutorResourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/learner'
    | '/login'
    | '/register'
    | '/select-role'
    | '/tutor/courses'
    | '/tutor/digital-twin'
    | '/tutor/overview'
    | '/tutor/resources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/learner'
    | '/login'
    | '/register'
    | '/select-role'
    | '/tutor/courses'
    | '/tutor/digital-twin'
    | '/tutor/overview'
    | '/tutor/resources'
  id:
    | '__root__'
    | '/'
    | '/learner'
    | '/login'
    | '/register'
    | '/select-role'
    | '/tutor/courses'
    | '/tutor/digital-twin'
    | '/tutor/overview'
    | '/tutor/resources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnerRoute: typeof LearnerRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SelectRoleRoute: typeof SelectRoleRoute
  TutorCoursesRoute: typeof TutorCoursesRoute
  TutorDigitalTwinRoute: typeof TutorDigitalTwinRoute
  TutorOverviewRoute: typeof TutorOverviewRoute
  TutorResourcesRoute: typeof TutorResourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-role': {
      id: '/select-role'
      path: '/select-role'
      fullPath: '/select-role'
      preLoaderRoute: typeof SelectRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner': {
      id: '/learner'
      path: '/learner'
      fullPath: '/learner'
      preLoaderRoute: typeof LearnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/resources': {
      id: '/tutor/resources'
      path: '/tutor/resources'
      fullPath: '/tutor/resources'
      preLoaderRoute: typeof TutorResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/overview': {
      id: '/tutor/overview'
      path: '/tutor/overview'
      fullPath: '/tutor/overview'
      preLoaderRoute: typeof TutorOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/digital-twin': {
      id: '/tutor/digital-twin'
      path: '/tutor/digital-twin'
      fullPath: '/tutor/digital-twin'
      preLoaderRoute: typeof TutorDigitalTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/courses': {
      id: '/tutor/courses'
      path: '/tutor/courses'
      fullPath: '/tutor/courses'
      preLoaderRoute: typeof TutorCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnerRoute: LearnerRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SelectRoleRoute: SelectRoleRoute,
  TutorCoursesRoute: TutorCoursesRoute,
  TutorDigitalTwinRoute: TutorDigitalTwinRoute,
  TutorOverviewRoute: TutorOverviewRoute,
  TutorResourcesRoute: TutorResourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
